{{- if .Values.fittrackee.appSecretKey.generate -}}
{{- $key := randAlphaNum 32 | b64enc  -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fittrackee.fullname" . }}-app-secret
  labels:
    {{- include "fittrackee.labels" . | nindent 4 }}
data:
  app-secret-key: {{ $key }}
{{- end }}
