---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fittrackee.fullname" . }}
  labels:
    {{- include "fittrackee.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.pvc.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}